### ISSUE TITLE
Oxygen template styling in Gmail in Chrome

### ISSUE THREAD

**Issue by munrocape** [sendwithus/templates#20] opened 2015-06-13 16:59 UTC
I tried sending one of the confirmation templates to myself. It appears as if the borders are missing in Chrome. They look fine in other browsers and clients. I've attached an image below.
![screen shot 2015-06-13 at 9 58 24 am](https://cloud.githubusercontent.com/assets/916774/8145190/ef78bec4-11b2-11e5-8956-c59d5f2718e5.png)

**Comment by kaytcat** [comment] 2015-07-20 08:24
Hello, I'm not able to reproduce this error. Which css inliner (https://github.com/sendwithus/templates#use-with-css-inliner) are you using? Could you please provide us with your code as well.

**Comment by bvanvugt** [comment] 2015-07-23 18:36
@munrocape Would like to get this take care of -- can you provide information on what inliner you're using?

Cheers!

**Comment by bvanvugt** [comment] 2015-07-27 22:30
Hey @munrocape  -- we're unable to reproduce this with our inliner, going to close the issue for now. 

But we'd be happy to investigate further if you're still experiencing the problem :)

**Closed by bvanvugt** 2015-07-27 22:30 UTC

**Comment by munrocape** [comment] 2015-07-27 22:35
Hey - sorry for the late response.

I was unfamiliar with inliners and did not know one was required. This was with the CSS still in the <style> block.

Thanks for the patience and following up.

Cheers
Zach

**Comment by bvanvugt** [comment] 2015-07-27 22:36
No problem, glad we got it sorted out!

**Comment by newscloud** [comment] 2016-05-27 05:52
You can see this in the Litmus preview https://litmus.com/checklist/public/2a61a03#gmailnew ... are you saying that inlining is required for Gmail compatibility? I like this theme and it works great elsewhere - but not in Gmail as is.
